name: Build and test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          path: build/libs/*.jar
  test:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
        - name: Checkout repo
          uses: actions/checkout@v2
        - name: Download artifacts
          uses: actions/download-artifact@v4
          with:
            path: extra-plugins/
            merge-multiple: true
        - name: Download Citizens Artifact
          run: wget https://ci.citizensnpcs.co/job/Citizens2/lastSuccessfulBuild/artifact/*zip*/archive.zip -P extra-plugins/
        - name: Extract Citizens Artifact
          run: unzip extra-plugins/archive.zip archive/dist/target/*.jar -d extra-plugins/
        - name: Move Citizens Artifact
          run: mv extra-plugins/archive/dist/target/*.jar extra-plugins/Citizens.jar
        - name: Run tests
          uses: SkriptLang/skript-test-action@v1.2
          with:
            test_script_directory: src/test/scripts
            skript_repo_ref: 2.11.0
            extra_plugins_directory: extra-plugins/